ARG OWNCLOUD_VERSION
FROM owncloud/server:${OWNCLOUD_VERSION}

# RUN rm /root/owncloud/config.php
# RUN rm /mnt/data/config/config.php

# COPY config1.php /root/owncloud/config.php
# COPY config2.php /mnt/data/config/config.php

# RUN su -c "php occ user:report" www-data
